version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    container_name: backend_service

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    container_name: frontend_service
    environment:
      - REACT_APP_GRAPHQL_API=http://backend:8000/graphql

